apiVersion: v1
kind: Service
metadata: 
  labels: 
    name: clowder-clowder
  name: clowder-clowder
spec:
  type: NodePort 
  ports:
    # the port that this service should serve on
    - port: 9000
      targetPort: 9000
      nodePort: 30291
      name: "clowder-ui"
  # label keys and values that must match in order to receive traffic for this service
  selector: 
    name: clowder-clowder
