apiVersion: v1
kind: Service
metadata: 
  labels: 
    name: clowder-elasticsearch
  name: clowder-elasticsearch
spec: 
  ports:
    # the port that this service should serve on
    - port: 9200
      targetPort: 9200
      name: "http-port"
    - port: 9300
      targetPort: 9300
      name: "transport-port"
  # label keys and values that must match in order to receive traffic for this service
  selector: 
    name: clowder-elasticsearch
