apiVersion: v1
kind: Service
metadata: 
  labels: 
    name: mongodb
  name: mongodb
spec: 
  ports:
    # the port that this service should serve on
    - port: 27017
      targetPort: 27017
      name: "db-port"
    - port: 28017
      targetPort: 28017
      name: "web-ui"
  # label keys and values that must match in order to receive traffic for this service
  selector: 
    name: mongodb
