apiVersion: v1
kind: Service
metadata: 
  labels: 
    name: terratoolsrv
  name: terratoolsrv
spec: 
  ports:
    # the port that this service should serve on
    - port: 8080
      targetPort: 8080
      name: "http"
  # label keys and values that must match in order to receive traffic for this service
  selector: 
    name: terratoolsrv
