apiVersion: v1
kind: PersistentVolume
metadata:
  name: elasticsearch-nfs
spec:
  capacity:
    storage: 1Mi
  accessModes:
    - ReadWriteMany
  nfs:
    server: 172.17.42.1
    path: "/data/elasticsearch"
