apiVersion: v1
kind: ReplicationController
metadata:
  name: elasticsearch-rc
  labels:
    component: elasticsearch
spec:
  replicas: 1
  selector:
    component: elasticsearch
  template:
    metadata:
      labels:
        component: elasticsearch
    spec:
      containers:
      - image: elasticsearch:2.1
        name: elasticsearch-rc
        ports:
        - containerPort: 9200
          name: db
          protocol: TCP
        - containerPort: 9300
          name: transport
          protocol: TCP
        volumeMounts:
        - name: es-persistent-storage
          mountPath: /usr/share/elasticsearch/data
      volumes:
      - name: es-persistent-storage
        hostPath:
           path: /data/elasticsearch
