apiVersion: v1
kind: ReplicationController
metadata:
  name: elasticsearch-rc
  labels:
    component: elasticsearch
spec:
  replicas: 1
  selector:
    component: elasticsearch
  template:
    metadata:
      labels:
        component: elasticsearch
    spec:
      containers:
      - image: elasticsearch:2.1
        name: elasticsearch-rc
        resources:
          # keep request = limit to keep this container in guaranteed class
          limits:
            cpu: 100m
          requests:
            cpu: 100m
        ports:
        - containerPort: 9200
          name: db
          protocol: TCP
        - containerPort: 9300
          name: transport
          protocol: TCP
        volumeMounts:
        - name: es-persistent-storage
          mountPath: /usr/share/elasticsearch/data
#        securityContext:
#          privileged: true
      volumes:
#      - name: es-persistent-storage
#        emptyDir: {}
#      - name: es-persistent-storage
#        persistentVolumeClaim:
#          claimName: elasticsearch-nfs
      - name: es-persistent-storage
        nfs:
          server: 172.17.42.1
          path: "/data/elasticsearch"
