apiVersion: v1
kind: Pod
metadata:
  name: test-clowder
  labels:
    name: clowder
spec:
  containers:
    - name: clowder-mongodb
      image: mongo:latest
      ports:
        -  containerPort: 27017
           name: "mongo-port"
    - name: clowder-rabbitmq
      image: rabbitmq:management
      ports:
        - containerPort: 5672
          name: "msg-bus"
        - containerPort: 15672
          name: "mgmt-port"
    - name: clowder-clowder
      image: clowder/clowder
      ports:
      - containerPort: 9000
        name: "clowder-ui"
      env:
      - name: SMTP_HOST
        value: "smtp.ncsa.illinois.edu"
      - name: CLOWDER_BRANCH
        value: "CATS-CORE0"
      - name: CLOWDER_BUILD
        value: "latestSuccessful"
      - name: CLOWDER_UPDATE
        value: "NO"
      - name: RABBITMQ_URI
        value: "amqp://guest:guest@localhost:5672/%2F"
      - name: RABBITMQ_EXCHANGE
        value: "clowder"
      - name: RABBITMQ_MGMT_PORT
        value: "15672"
    - name: clowder-image-preview
      image: clowder/image-preview
      env:
      - name: RABBITMQ_URI
        value: "amqp://guest:guest@localhost:5672/%2F"
      - name: RABBITMQ_EXCHANGE
        value: "clowder"
      - name: RABBITMQ_VHOST
        value: "%2F"
      - name: RABBITMQ_QUEUE
        value: "ncsa.image.preview"
      - name: RABBITMQ_PORT_5672_TCP_ADDR
        value: "127.0.0.1"
      - name: RABBITMQ_PORT_5672_TCP_PORT
        value: "5672"
      - name: RABBITMQ_PORT_15672_TCP_ADDR
        value: "127.0.0.1"
      - name: RABBITMQ_PORT_15672_TCP_PORT
        value: "15672"
    - name: clowder-video-preview
      image: clowder/video-preview
      env:
      - name: RABBITMQ_URI
        value: "amqp://guest:guest@localhost:5672/%2F"
      - name: RABBITMQ_EXCHANGE
        value: "clowder"
      - name: RABBITMQ_VHOST
        value: "%2F"
      - name: RABBITMQ_QUEUE
        value: "ncsa.video.preview"
      - name: RABBITMQ_PORT_5672_TCP_ADDR
        value: "127.0.0.1"
      - name: RABBITMQ_PORT_5672_TCP_PORT
        value: "5672"
    - name: clowder-plantcv
      image: clowder/plantcv
      env:
      - name: RABBITMQ_URI
        value: "amqp://guest:guest@localhost:5672/%2F"
      - name: RABBITMQ_EXCHANGE
        value: "clowder"
      - name: RABBITMQ_VHOST
        value: "%2F"
      - name: RABBITMQ_QUEUE
        value: "terra.plantcv"
      - name: RABBITMQ_PORT_5672_TCP_ADDR
        value: "127.0.0.1"
      - name: RABBITMQ_PORT_5672_TCP_PORT
        value: "5672"
