apiVersion: v1
kind: ReplicationController
metadata:
  name: kibana-rc
  labels:
    app: kibana
spec:
  replicas: 1
  selector:
    app: kibana
  template:
    metadata:
      labels:
        app: kibana
    spec:
      containers:
      - name: kibana
        image: kibana
        ports:
        - containerPort: 5601
        env:
          - name: "ELASTICSEARCH_URL"
            value: "http://$(ELASTICSEARCH_SERVICE_HOST):$(ELASTICSEARCH_SERVICE_PORT_HTTP)"
