elasticsearch:
  image: elasticsearch:latest
  command: elasticsearch -Des.network.host=0.0.0.0
  ports:
    - "9200:9200"
    - "9300:9300"
logstash:
  image: logstash:latest
  command: logstash -e 'output { elasticsearch { hosts => \"elasticsaerch\" } } input { tcp { port => 5000 type => syslog } udp { port => 5000 type => syslog } }'
  ports:
    - "5000:5000"
  links:
    - elasticsearch
kibana:
  image: kibana:latest
  ports:
    - "5601:5601"
  links:
    - elasticsearch
