elasticsearch:
  image: elasticsearch:latest
  command: elasticsearch -Des.network.host=0.0.0.0
  ports:
    - "9200:9200"
    - "9300:9300"
logstash:
  image: logstash:latest
  command: logstash -f /nds/src/services/ops/lma/elk/logstash/logstash.conf
  volumes_from:
    - NDSSRC
  ports:
    - "5000:5000"
  links:
    - elasticsearch
kibana:
  image: kibana:latest
  ports:
    - "5601:5601"
  links:
    - elasticsearch
