#
# swagger-editor - tool for top-down rest api generation
#
IMAGES	=	swagger-editor
#Dockerfile.swagger-editor.url := 'https://raw.githubusercontent.com/swagger-api/swagger-editor/master/Dockerfile

include $(NDSLABS_SRC)/devtools/Makefiles/Makefile.nds

