apiVersion: v1
kind: Service
metadata:
  name: logstash
  labels:
    app: logstash
spec:
  ports:
  - port: 5000
    protocol: TCP
    name: tcp
  - port: 5000
    protocol: UDP
    name: udp
  selector:
    app: logstash
