apiVersion: v1
kind: Pod
metadata:
  name: logstash
  labels:
    app: logstash
spec:
  containers:
  - name: logstash
    image: logstash
    command: [ "logstash", "-e"]
    args: ["output { elasticsearch { hosts => \"$(ELASTICSEARCH_SERVICE_HOST):$(ELASTICSEARCH_SERVICE_PORT_HTTP)\" } } input { tcp { port => 5000 type => syslog } }"]
  volumes:
  - emptyDir:
      medium: ""
    name: "storage"
