apiVersion: v1
kind: ReplicationController
metadata:
  name: clowder
  labels:
    name: clowder
spec:
  replicas: 1
  selector:
    name: clowder
  template:
    metadata:
      labels:
        name: clowder
    spec:
      containers:
      - name: clowder
        image: ndslabs/clowder:0.9.1
        ports:
        - containerPort: 9000
        env:
        - name: SMTP_HOST
          value: "smtp.ncsa.illinois.edu"
        - name: ELASTICSEARCH_CLUSTERNAME
          value: "clowder"
        - name: ELASTICSEARCH_SERVER
          value: "$(ELASTICSEARCH_PORT_9300_TCP_ADDR)"
        - name: ELASTICSEARCH_PORT
          value: "$(ELASTICSEARCH_PORT_9300_TCP_PORT)"
        - name: RABBITMQ_EXCHANGE
          value: "clowder"
