apiVersion: v1
kind: ReplicationController
metadata:
  name: mongodb
  labels:
    name: mongodb
spec:
  replicas: 1
  selector:
    name: mongodb
  template:
    metadata:
      labels:
        name: mongodb
    spec:
      containers:
      - name: mongodb
        image: mongo:latest
        ports:
        - containerPort: 27017
	# - containerPort: 28017
        # args:
        # - "--rest"
        # - "--httpinterface" 
