apiVersion: v1
kind: ReplicationController
metadata:
  name: video-preview
  labels:
    name: video-preview
spec:
  replicas: 1
  selector:
    name: video-preview
  template:
    metadata:
      labels:
        name: video-preview
    spec:
      containers:
      - name: video-preview
        image: ndslabs/video-preview:0.9.1
        env:
        - name: RABBITMQ_EXCHANGE
          value: "clowder"
        - name: RABBITMQ_VHOST
          value: "%2F"
        - name: RABBITMQ_QUEUE
          value: "ncsa.video.preview"
