heat_template_version: 2013-05-23
description: >
  Deploy a small CoreOS cluster.
parameters:
  network_id:
    type: string
    label: Network ID
    description: ID of existing Neutron network to use
    default: <ID of Neutron network to which instances should connect>
  image_id:
    type: string
    label: Glance Image ID
    description: ID of existing Glance image to use
    default: <ID of CoreOS Glance image>
  key_name:
    type: string
    label: KeyPair Name to Inject
resources:
  instance0_port0:
    type: OS::Neutron::Port
    properties:
      admin_state_up: true
      network_id: { get_param: network_id }
      security_groups:
        - <ID of security group to apply to this Neutron port>
  instance0:
    type: OS::Nova::Server
    properties:
      name: coreos-04
      image: { get_param: image_id }
      flavor: m1.small
      networks:
        - port: { get_resource: instance0_port0 }
      key_name: { get_param:  key_name }
      user_data_format: RAW
      user_data: |
        #cloud-config
        coreos:
          etcd:
            discovery: https://discovery.etcd.io/<unique cluster ID here>
            addr: $private_ipv4:4001
            peer-addr: $private_ipv4:7001
          units:
            - name: etcd.service
              command: start
            - name: fleet.service
              command: start
