FROM ubuntu
RUN apt-get -y update && apt-get -y install wget docker.io python python-dev python-pip && pip install flask-restful
#RUN apt-get -y update && apt-get install python-pip && pip install flask-restful
#&& pip install -y flask-restful

COPY FILES.pysherpactl /
#COPY pysherpactl-usage /usr/bin
#CMD pysherpactl-usage


