#!/bin/bash
debug() {
echo $*
}

ORIG_ARGS=$*

debug $*
if [ "$1" == "DVOL" ] ; then
    DVOLNAME="$2"
    shift; shift;
fi
debug $*

if [ "$1" == "DPATH" ] ; then
    DVOLPATH="$2"
    shift; shift;
fi
debug $*

if [ "$1" == "DSRC" ] ; then
    DVOLSRC="$2"
    shift; shift;
fi
debug $*

if [ "$1" == "DXFRCMD" ] ; then
    DXFRCMD="$2"
    shift; shift;
fi
debug $*

docker create --name $DVOLNAME -v $DVOLPATH scratch none
docker run --rm --volumes-from $DVOLNAME sherpa bash -c "$DXFRCMD"
docker run $*
