FROM ubuntu
RUN apt-get -y update \
    && apt-get -y install curl unzip docker.io python python-dev python-pip \
    && pip install flask-restful \
    && apt-get clean all \
    && rm -rf /var/lib/apt/lists/* /tmp/* /var/tmp/* \
    ;
COPY FILES.terratoolsrv /
CMD /usr/local/bin/usage

