FROM ndslabs/irods-icat:4.1.3
MAINTAINER willis8@illinois.edu

COPY FILES.dataverse-icat/dvn_staging.r /etc/irods
COPY FILES.dataverse-icat/entrypoint.sh /

VOLUME /var/lib/postgresql/9.3/main
VOLUME /var/lib/irods/Vault

EXPOSE 1247
CMD ["/entrypoint.sh", "icat"]
