apiVersion: v1
kind: ReplicationController
metadata:
  name: postgres-rc
spec:
  replicas: 1
  selector:
    component: postgres
  template:
    metadata:
      labels:
        component: postgres
    spec:
      containers:
      - name: postgres
        image: postgres:9.3
        ports:
        - containerPort: 5432
          protocol: TCP
      volumes:
      - emptyDir:
          medium: ""
        name: "storage"
